"""Build the three manuscript variants from one source.

  auditable-by-design.tex  submission: main text only (TDSC limit: 12 pages including references and biography)
  supplement.tex           supplementary material; cross-references to and from the main text via xr-hyper
  arxiv.tex                extended version: main text with the supplementary sections as appendices

Sources (edit these, not the generated files): preamble.tex, sections/main_*.tex, sections/supp_*.tex,
sections/bio.tex, references.tex (every \\bibitem).  Each bibliography lists only the works cited in that
variant, numbered in first-citation order; the supplement cites with the main text's numbers ([S1], ... for
works cited only in the supplement) and lists its references in that numerical order.  In the arXiv version
references to supplementary sections read "Appendix X", and the Acknowledgment follows the appendices.

Usage: python3 assemble.py        (then pdflatex main, supplement, main, supplement; arxiv twice)
"""

import glob
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
TITLE = 'Auditable by Design: Secure AI-Assisted Migration\\\\ to Post-Quantum Cryptography'
GENERATED = '% GENERATED by assemble.py -- edit preamble.tex, sections/*.tex or references.tex instead.\n'


def read(path):
    with open(os.path.join(HERE, path)) as fh:
        return fh.read()


def sections(prefix):
    paths = sorted(glob.glob(os.path.join(HERE, 'sections', f'{prefix}_*.tex')))
    # a file holding only comments (a region that moved nothing to the supplement) is skipped
    return [os.path.relpath(p, HERE)[:-4] for p in paths if re.sub(r'(?<!\\)%.*', '', read(p)).strip()]


def cite_order(texts):
    order = []
    for text in texts:
        text = re.sub(r'(?<!\\)%.*', '', text)
        for m in re.finditer(r'\\cite\{([^}]*)\}', text):
            for key in (k.strip() for k in m.group(1).split(',')):
                if key and key not in order:
                    order.append(key)
    return order


def bibitems():
    body = read('references.tex')
    items = {}
    for m in re.finditer(r'\\bibitem\{([^}]*)\}(.*?)(?=\\bibitem\{|\Z)', body, re.S):
        items[m.group(1)] = m.group(2).strip()
    return items


def bibliography(keys, items, labels=None):
    missing = [k for k in keys if k not in items]
    if missing:
        raise SystemExit(f'cited but not in references.tex: {missing}')
    width = max((labels or {}).values(), key=len, default=str(len(keys)))
    out = ['\\begin{thebibliography}{' + width + '}']
    for k in keys:
        label = f'[{labels[k]}]' if labels else ''
        out.append(f'\\bibitem{label}{{{k}}}\n{items[k]}')
    out.append('\\end{thebibliography}')
    return '\n'.join(out) + '\n'


def inputs(names):
    return ''.join(f'\\input{{{n}}}\n' for n in names)


def appendix_labels(texts):
    """Labels of the supplementary sections, which become appendices in the arXiv version."""
    return {m.group(1) for t in texts
            for m in re.finditer(r'\\section\{[^\n]*\}\s*\\label\{([^}]*)\}', t)}


def arxiv_text(name, app):
    """Read a section for the arXiv version: a reference to a supplementary section becomes
    'Appendix~\\ref{..}' (IEEE style), and the remaining mentions of the supplement become 'appendix'."""
    text = read(name + '.tex')
    lab = r'\\ref\{(' + '|'.join(sorted(map(re.escape, app))) + r')\}' if app else r'(?!)'
    text = re.sub(r'Sections~' + lab + r'(--|~and~| and~)' + lab, r'Appendices~\\ref{\1}\2\\ref{\3}', text)
    text = re.sub(r'Section~' + lab, r'Appendix~\\ref{\1}', text)
    text = re.sub(r'(Appendi(?:x|ces)~\\ref\{[^}]*\}(?:(?:--|~and~| and~)\\ref\{[^}]*\})?)'
                  r'(?:,\s+supplementary material|\s+(?:of|in) the supplementary material|\s+\(supplementary material\))',
                  r'\1', text)
    text = text.replace('supplementary material', 'appendix').replace('Supplementary material', 'Appendix')
    return text


def split_acknowledgment(text):
    """Split off the Acknowledgment (and the \\balance after it) so that the arXiv version can place it
    after the appendices, in the IEEEtran order Conclusion, Appendices, Acknowledgment, References."""
    m = re.search(r'\\section\*\{Acknowledg[^}]*\}.*?(?=\\section|\Z)', text, re.S)
    return (text[:m.start()] + text[m.end():], m.group(0)) if m else (text, '')


def ack_file():
    """Optional sections/ack.tex (Acknowledgment kept outside main_*.tex); '' when absent."""
    return 'sections/ack' if os.path.exists(os.path.join(HERE, 'sections', 'ack.tex')) else ''


def main():
    items = bibitems()
    main_secs, supp_secs = sections('main'), sections('supp')
    ack_secs = [ack_file()] if ack_file() else []
    main_texts = [read(n + '.tex') for n in main_secs + ack_secs]
    supp_texts = [read(n + '.tex') for n in supp_secs]

    main_keys = cite_order(main_texts)
    with open(os.path.join(HERE, 'bib_main.tex'), 'w') as fh:
        fh.write(GENERATED + bibliography(main_keys, items))

    supp_keys = cite_order(supp_texts)
    extra = [k for k in supp_keys if k not in main_keys]
    labels = {k: str(main_keys.index(k) + 1) for k in supp_keys if k in main_keys}
    labels.update({k: f'S{i + 1}' for i, k in enumerate(extra)})
    # listed in numerical order: main-text numbers first, then S1, S2, ...
    supp_list = sorted((k for k in supp_keys if k in main_keys), key=main_keys.index) + extra
    with open(os.path.join(HERE, 'bib_supp.tex'), 'w') as fh:
        fh.write(GENERATED + (bibliography(supp_list, items, labels) if supp_keys else ''))
    if not extra:
        extra_note = ''
    elif len(extra) == 1:
        extra_note = '; reference [S1] is cited only in this supplement'
    else:
        extra_note = f'; references [S1]--[S{len(extra)}] are cited only in this supplement'

    arxiv_keys = cite_order(main_texts + supp_texts)
    with open(os.path.join(HERE, 'bib_arxiv.tex'), 'w') as fh:
        fh.write(GENERATED + bibliography(arxiv_keys, items))

    # submission: balance the columns of the last page (after the Acknowledgment, before the references)
    # unless a section already calls \balance.  Not added to the arXiv version, whose last page depends on
    # the appendices: when the references fill a page, \balance splits the biography across the columns.
    bal = '' if any(re.search(r'^[^%\n]*\\balance\b', t, re.M) for t in main_texts) else '\\balance\n'

    head = '\\documentclass[journal]{IEEEtran}\n'
    with open(os.path.join(HERE, 'auditable-by-design.tex'), 'w') as fh:
        fh.write(GENERATED + head + '\\usepackage{xr-hyper}\n\\externaldocument[][nocite]{supplement}\n'
                 '\\input{preamble}\n\\begin{document}\n' + inputs(main_secs + ack_secs)
                 + bal + '\\input{bib_main}\n\\input{sections/bio}\n\\end{document}\n')

    with open(os.path.join(HERE, 'supplement.tex'), 'w') as fh:
        fh.write(GENERATED + head + '\\usepackage{xr-hyper}\n\\externaldocument[][nocite]{auditable-by-design}\n'
                 '\\input{preamble}\n'
                 # the hyphen of S-V is boxed so that a reference never breaks the line after "S-"
                 '\\renewcommand{\\thesection}{\\texorpdfstring{S\\mbox{-}}{S-}\\Roman{section}}\n'
                 '\\renewcommand{\\thetable}{S\\mbox{-}\\Roman{table}}\n'
                 '\\renewcommand{\\thefigure}{S\\arabic{figure}}\n'
                 '\\renewcommand{\\theequation}{S\\arabic{equation}}\n'
                 '\\AtBeginDocument{\\renewcommand{\\thelstlisting}{S\\arabic{lstlisting}}}\n'
                 '\\begin{document}\n'
                 f'\\title{{Supplementary Material for\\\\ ``{TITLE}\'\'}}\n'
                 '\\author{Sergey~Mkrtchyan}\n\\markboth{Supplementary Material}{Mkrtchyan: Auditable by Design}\n'
                 '\\maketitle\n'
                 '\\noindent Section, table, figure, and equation numbers without the prefix S refer to the '
                 f'main text. Reference numbers are those of the main text{extra_note}.\n\n'
                 + inputs(supp_secs) + '\\input{bib_supp}\n\\end{document}\n')

    app = appendix_labels(supp_texts)
    body, ack = split_acknowledgment(''.join(arxiv_text(n, app) + '\n' for n in main_secs))
    ack += ''.join(arxiv_text(n, app) + '\n' for n in ack_secs)
    appendix = ''.join(arxiv_text(n, app) + '\n' for n in supp_secs)
    with open(os.path.join(HERE, 'arxiv.tex'), 'w') as fh:
        fh.write(GENERATED + head + read('preamble.tex') + '\\begin{document}\n' + body
                 + ('\\appendices\n' + appendix if appendix else '') + ack
                 + '\\input{bib_arxiv}\n' + read('sections/bio.tex') + '\\end{document}\n')

    print(f'main: {len(main_secs)} sections, {len(main_keys)} references; '
          f'supplement: {len(supp_secs)} sections, {len(supp_keys)} cited ({len(extra)} only there); '
          f'arxiv: {len(arxiv_keys)} references')


if __name__ == '__main__':
    main()
